<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="NetCord" Version="1.0.0-alpha.444" />
    <PackageReference Include="NetCord.Hosting" Version="1.0.0-alpha.444" />
    <PackageReference Include="NetCord.Hosting.AspNetCore" Version="1.0.0-alpha.444" />
    <PackageReference Include="NetCord.Hosting.Services" Version="1.0.0-alpha.444" />
    <PackageReference Include="NetCord.Services" Version="1.0.0-alpha.444" />
	<None Update=".env">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</None>
  </ItemGroup>

</Project>
